fixtures:
  repositories:
    stdlib: 
      repo: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
      ref: "3.2.0"
    logrotate:
      repo: "git://github.com/puppetlabs/puppetlabs-concat.git"
      ref: "1.0.0"
  symlinks:
    "nfs": "#{source_dir}"
